repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: lint-js
      name: ESLint
      entry: npm run lint
      language: system
      pass_filenames: false
      stages: [pre-commit]
      types_or: [javascript, jsx]
